export type CourseProvider =
  | "DeepLearning.AI"
  | "Coursera"
  | "Udemy"
  | "MIT OpenCourseWare"
  | "YouTube"
  | "Google"
  | "IBM"
  | "Microsoft"
  | "Amazon";

export type CourseLevel = "beginner" | "intermediate" | "advanced";
export type CourseCost = "free" | "freemium" | "paid";
export type CourseFormat = "course" | "specialization" | "certificate" | "tutorial" | "playlist";

export type LearningCourse = {
  id: string;
  provider: CourseProvider;
  title: string;
  url: string;
  skills: string[];
  level: CourseLevel;
  cost: CourseCost;
  durationHours: number;
  format: CourseFormat;
  description: string;
};

export const courses = [
  {
    id: "deeplearning-ai-ml-specialization",
    provider: "DeepLearning.AI",
    title: "Machine Learning Specialization",
    url: "https://www.deeplearning.ai/courses/machine-learning-specialization/",
    skills: ["machine-learning", "python", "data-analysis"],
    level: "beginner",
    cost: "freemium",
    durationHours: 95,
    format: "specialization",
    description: "Andrew Ng's foundational machine learning path covering supervised, unsupervised, and recommender systems.",
  },
  {
    id: "deeplearning-ai-deep-learning-specialization",
    provider: "DeepLearning.AI",
    title: "Deep Learning Specialization",
    url: "https://www.deeplearning.ai/courses/deep-learning-specialization/",
    skills: ["machine-learning", "python"],
    level: "intermediate",
    cost: "freemium",
    durationHours: 80,
    format: "specialization",
    description: "Build neural networks, CNNs, sequence models, and practical deep learning workflows.",
  },
  {
    id: "deeplearning-ai-math-for-ml",
    provider: "DeepLearning.AI",
    title: "Mathematics for Machine Learning and Data Science",
    url: "https://www.deeplearning.ai/courses/mathematics-for-machine-learning-and-data-science-specialization/",
    skills: ["machine-learning", "data-analysis"],
    level: "beginner",
    cost: "freemium",
    durationHours: 60,
    format: "specialization",
    description: "A practical math foundation for calculus, linear algebra, statistics, and probability in ML.",
  },
  {
    id: "deeplearning-ai-data-analytics",
    provider: "DeepLearning.AI",
    title: "Data Analytics Professional Certificate",
    url: "https://www.deeplearning.ai/courses/data-analytics-professional-certificate/",
    skills: ["data-analysis", "sql", "python"],
    level: "beginner",
    cost: "freemium",
    durationHours: 80,
    format: "certificate",
    description: "Hands-on analytics training with industry tools for extracting insights and communicating decisions.",
  },
  {
    id: "deeplearning-ai-ai-for-everyone",
    provider: "DeepLearning.AI",
    title: "AI For Everyone",
    url: "https://www.deeplearning.ai/courses/ai-for-everyone/",
    skills: ["machine-learning", "strategic-planning", "stakeholder-management"],
    level: "beginner",
    cost: "freemium",
    durationHours: 6,
    format: "course",
    description: "A concise business-oriented introduction to AI strategy, opportunities, and limitations.",
  },
  {
    id: "deeplearning-ai-generative-ai-software-development",
    provider: "DeepLearning.AI",
    title: "Generative AI for Software Development",
    url: "https://www.deeplearning.ai/courses/generative-ai-for-software-development/",
    skills: ["python", "javascript", "typescript"],
    level: "intermediate",
    cost: "freemium",
    durationHours: 20,
    format: "course",
    description: "Use generative AI for code generation, testing, refactoring, and delivery workflows.",
  },
  {
    id: "google-data-analytics-certificate",
    provider: "Google",
    title: "Google Data Analytics Professional Certificate",
    url: "https://grow.google/certificates/data-analytics/",
    skills: ["data-analysis", "sql", "tableau", "presentation"],
    level: "beginner",
    cost: "freemium",
    durationHours: 180,
    format: "certificate",
    description: "Google's structured path for data cleaning, analysis, visualization, and stakeholder presentation.",
  },
  {
    id: "google-advanced-data-analytics-certificate",
    provider: "Google",
    title: "Google Advanced Data Analytics Professional Certificate",
    url: "https://grow.google/certificates/advanced-data-analytics/",
    skills: ["python", "data-analysis", "machine-learning"],
    level: "intermediate",
    cost: "freemium",
    durationHours: 180,
    format: "certificate",
    description: "Advanced analytics, Python, statistics, regression, and machine learning for analysts.",
  },
  {
    id: "google-project-management-certificate",
    provider: "Google",
    title: "Google Project Management Professional Certificate",
    url: "https://grow.google/certificates/project-management/",
    skills: ["project-management", "agile", "stakeholder-management"],
    level: "beginner",
    cost: "freemium",
    durationHours: 120,
    format: "certificate",
    description: "A practical project management certificate covering planning, execution, agile, and stakeholder work.",
  },
  {
    id: "google-cloud-digital-leader",
    provider: "Google",
    title: "Cloud Digital Leader Learning Path",
    url: "https://www.cloudskillsboost.google/paths/9",
    skills: ["strategic-planning", "stakeholder-management"],
    level: "beginner",
    cost: "freemium",
    durationHours: 12,
    format: "course",
    description: "A business-first Google Cloud path for understanding cloud value, transformation, and data use cases.",
  },
  {
    id: "google-cloud-data-analyst",
    provider: "Google",
    title: "Data Analyst Learning Path",
    url: "https://www.cloudskillsboost.google/paths/18",
    skills: ["data-analysis", "sql", "python"],
    level: "intermediate",
    cost: "freemium",
    durationHours: 45,
    format: "course",
    description: "Google Cloud analytics training across data querying, transformation, visualization, and insight delivery.",
  },
  {
    id: "google-tensorflow-learning",
    provider: "Google",
    title: "TensorFlow Learn",
    url: "https://www.tensorflow.org/learn",
    skills: ["machine-learning", "python"],
    level: "intermediate",
    cost: "free",
    durationHours: 25,
    format: "tutorial",
    description: "Official TensorFlow tutorials and guides for model building, training, and deployment concepts.",
  },
  {
    id: "microsoft-azure-fundamentals",
    provider: "Microsoft",
    title: "Microsoft Azure Fundamentals",
    url: "https://learn.microsoft.com/en-us/training/paths/microsoft-azure-fundamentals-describe-cloud-concepts/",
    skills: ["azure"],
    level: "beginner",
    cost: "free",
    durationHours: 8,
    format: "course",
    description: "Official Microsoft Learn path for cloud concepts, Azure architecture, and core services.",
  },
  {
    id: "microsoft-power-bi-learning-path",
    provider: "Microsoft",
    title: "Power BI Learning Path Directory",
    url: "https://learn.microsoft.com/en-us/power-bi/fundamentals/power-bi-learning-path-directory",
    skills: ["power-bi", "data-analysis", "presentation"],
    level: "beginner",
    cost: "free",
    durationHours: 35,
    format: "course",
    description: "Official Power BI learning paths for data preparation, modeling, reporting, and dashboard delivery.",
  },
  {
    id: "microsoft-data-analyst-power-bi",
    provider: "Microsoft",
    title: "Get Started with Microsoft Data Analytics",
    url: "https://learn.microsoft.com/en-us/training/paths/data-analytics-microsoft/",
    skills: ["power-bi", "data-analysis", "excel"],
    level: "beginner",
    cost: "free",
    durationHours: 12,
    format: "course",
    description: "Microsoft Learn modules for data analytics concepts, Power BI, and report creation.",
  },
  {
    id: "microsoft-typescript",
    provider: "Microsoft",
    title: "Build JavaScript Applications with TypeScript",
    url: "https://learn.microsoft.com/en-us/training/paths/build-javascript-applications-typescript/",
    skills: ["typescript", "javascript"],
    level: "intermediate",
    cost: "free",
    durationHours: 10,
    format: "course",
    description: "Official TypeScript learning path for typed JavaScript application development.",
  },
  {
    id: "microsoft-react-web-apps",
    provider: "Microsoft",
    title: "Create Web Apps with React",
    url: "https://learn.microsoft.com/en-us/training/paths/react/",
    skills: ["react", "javascript", "typescript"],
    level: "beginner",
    cost: "free",
    durationHours: 8,
    format: "course",
    description: "Microsoft Learn modules for React components, state, and modern web app foundations.",
  },
  {
    id: "microsoft-security-compliance-identity",
    provider: "Microsoft",
    title: "Security, Compliance, and Identity Fundamentals",
    url: "https://learn.microsoft.com/en-us/training/paths/describe-concepts-of-security-compliance-identity/",
    skills: ["risk-management", "process-improvement"],
    level: "beginner",
    cost: "free",
    durationHours: 8,
    format: "course",
    description: "A foundational Microsoft path for security, compliance, identity, and risk concepts.",
  },
  {
    id: "aws-cloud-practitioner-learning-plan",
    provider: "Amazon",
    title: "Cloud Practitioner Learning Plan",
    url: "https://aws.amazon.com/training/learn-about/cloud-practitioner/",
    skills: ["aws"],
    level: "beginner",
    cost: "free",
    durationHours: 12,
    format: "course",
    description: "AWS expert-built training for cloud fundamentals, core services, and certification readiness.",
  },
  {
    id: "aws-solutions-architect-learning-plan",
    provider: "Amazon",
    title: "Solutions Architect Learning Plan",
    url: "https://aws.amazon.com/training/learn-about/architect/",
    skills: ["aws", "strategic-planning"],
    level: "intermediate",
    cost: "free",
    durationHours: 40,
    format: "course",
    description: "AWS architecture training for designing resilient, secure, and cost-aware cloud solutions.",
  },
  {
    id: "aws-machine-learning-learning-plan",
    provider: "Amazon",
    title: "Machine Learning Learning Plan",
    url: "https://aws.amazon.com/training/learn-about/machine-learning/",
    skills: ["aws", "machine-learning", "python"],
    level: "intermediate",
    cost: "free",
    durationHours: 30,
    format: "course",
    description: "AWS training for machine learning workflows, cloud ML services, and applied AI use cases.",
  },
  {
    id: "aws-data-analytics-learning-plan",
    provider: "Amazon",
    title: "Data Analytics Learning Plan",
    url: "https://aws.amazon.com/training/learn-about/data-analytics/",
    skills: ["aws", "data-analysis", "sql"],
    level: "intermediate",
    cost: "free",
    durationHours: 30,
    format: "course",
    description: "AWS analytics training for data lakes, warehousing, querying, and visualization pipelines.",
  },
  {
    id: "ibm-data-science-certificate",
    provider: "IBM",
    title: "IBM Data Science Professional Certificate",
    url: "https://www.coursera.org/professional-certificates/ibm-data-science",
    skills: ["python", "sql", "data-analysis", "machine-learning"],
    level: "beginner",
    cost: "freemium",
    durationHours: 160,
    format: "certificate",
    description: "A broad IBM certificate covering Python, SQL, data analysis, visualization, and machine learning.",
  },
  {
    id: "ibm-ai-engineering-certificate",
    provider: "IBM",
    title: "IBM AI Engineering Professional Certificate",
    url: "https://www.coursera.org/professional-certificates/ai-engineer",
    skills: ["machine-learning", "python"],
    level: "intermediate",
    cost: "freemium",
    durationHours: 120,
    format: "certificate",
    description: "IBM's applied AI engineering path for machine learning, deep learning, and model deployment.",
  },
  {
    id: "ibm-data-analyst-certificate",
    provider: "IBM",
    title: "IBM Data Analyst Professional Certificate",
    url: "https://www.coursera.org/professional-certificates/ibm-data-analyst",
    skills: ["data-analysis", "excel", "sql", "python"],
    level: "beginner",
    cost: "freemium",
    durationHours: 120,
    format: "certificate",
    description: "IBM's data analyst path across spreadsheets, SQL, Python, dashboards, and applied analytics projects.",
  },
  {
    id: "ibm-project-manager-certificate",
    provider: "IBM",
    title: "IBM Project Manager Professional Certificate",
    url: "https://www.coursera.org/professional-certificates/ibm-project-manager",
    skills: ["project-management", "agile", "scrum"],
    level: "beginner",
    cost: "freemium",
    durationHours: 100,
    format: "certificate",
    description: "A project management certificate covering planning, delivery, agile practices, and portfolio evidence.",
  },
  {
    id: "coursera-google-business-intelligence",
    provider: "Coursera",
    title: "Google Business Intelligence Professional Certificate",
    url: "https://www.coursera.org/professional-certificates/google-business-intelligence",
    skills: ["data-analysis", "tableau", "stakeholder-management"],
    level: "intermediate",
    cost: "freemium",
    durationHours: 70,
    format: "certificate",
    description: "A BI-focused certificate for data models, dashboards, reporting, and stakeholder decision support.",
  },
  {
    id: "coursera-wharton-business-foundations",
    provider: "Coursera",
    title: "Business Foundations Specialization",
    url: "https://www.coursera.org/specializations/wharton-business-foundations",
    skills: ["strategic-planning", "budgeting", "negotiation"],
    level: "beginner",
    cost: "freemium",
    durationHours: 80,
    format: "specialization",
    description: "Wharton-led foundations in finance, marketing, operations, and business strategy.",
  },
  {
    id: "coursera-uva-darden-design-thinking",
    provider: "Coursera",
    title: "Design Thinking for Innovation",
    url: "https://www.coursera.org/learn/uva-darden-design-thinking-innovation",
    skills: ["strategic-planning", "stakeholder-management", "presentation"],
    level: "beginner",
    cost: "freemium",
    durationHours: 12,
    format: "course",
    description: "A practical introduction to design thinking, problem framing, and innovation communication.",
  },
  {
    id: "coursera-negotiation-success",
    provider: "Coursera",
    title: "Successful Negotiation: Essential Strategies and Skills",
    url: "https://www.coursera.org/learn/negotiation-skills",
    skills: ["negotiation", "presentation", "stakeholder-management"],
    level: "beginner",
    cost: "freemium",
    durationHours: 16,
    format: "course",
    description: "A structured negotiation course covering preparation, bargaining, closing, and dispute resolution.",
  },
  {
    id: "coursera-leading-people-teams",
    provider: "Coursera",
    title: "Leading People and Teams Specialization",
    url: "https://www.coursera.org/specializations/leading-teams",
    skills: ["leadership", "people-management", "stakeholder-management"],
    level: "intermediate",
    cost: "freemium",
    durationHours: 60,
    format: "specialization",
    description: "Leadership training for motivating teams, managing talent, influencing, and building culture.",
  },
  {
    id: "coursera-risk-management",
    provider: "Coursera",
    title: "Risk Management Specialization",
    url: "https://www.coursera.org/specializations/risk-management",
    skills: ["risk-management", "strategic-planning"],
    level: "intermediate",
    cost: "freemium",
    durationHours: 60,
    format: "specialization",
    description: "A practical path for risk identification, analysis, mitigation, and business resilience.",
  },
  {
    id: "mit-introduction-to-computer-science-python",
    provider: "MIT OpenCourseWare",
    title: "Introduction to Computer Science and Programming in Python",
    url: "https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/",
    skills: ["python"],
    level: "beginner",
    cost: "free",
    durationHours: 60,
    format: "course",
    description: "MIT's rigorous Python and computational thinking foundation for technical career changers.",
  },
  {
    id: "mit-introduction-to-algorithms",
    provider: "MIT OpenCourseWare",
    title: "Introduction to Algorithms",
    url: "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/",
    skills: ["python", "javascript", "process-improvement"],
    level: "intermediate",
    cost: "free",
    durationHours: 80,
    format: "course",
    description: "A serious algorithms foundation for software, analytics, and technical problem solving.",
  },
  {
    id: "mit-machine-learning",
    provider: "MIT OpenCourseWare",
    title: "Machine Learning",
    url: "https://ocw.mit.edu/courses/6-867-machine-learning-fall-2006/",
    skills: ["machine-learning", "data-analysis"],
    level: "advanced",
    cost: "free",
    durationHours: 70,
    format: "course",
    description: "A rigorous ML course for learners ready to work through theory and mathematical foundations.",
  },
  {
    id: "mit-managerial-psychology",
    provider: "MIT OpenCourseWare",
    title: "Managerial Psychology",
    url: "https://ocw.mit.edu/courses/15-301-managerial-psychology-fall-2006/",
    skills: ["leadership", "people-management", "presentation"],
    level: "intermediate",
    cost: "free",
    durationHours: 35,
    format: "course",
    description: "MIT material on organizational behavior, leadership, and people dynamics.",
  },
  {
    id: "mit-project-management",
    provider: "MIT OpenCourseWare",
    title: "Project Management",
    url: "https://ocw.mit.edu/courses/1-040-project-management-spring-2009/",
    skills: ["project-management", "risk-management", "budgeting"],
    level: "intermediate",
    cost: "free",
    durationHours: 35,
    format: "course",
    description: "A rigorous project management foundation covering planning, controls, risk, and delivery tradeoffs.",
  },
  {
    id: "youtube-freecodecamp-python",
    provider: "YouTube",
    title: "Python for Beginners",
    url: "https://www.youtube.com/@freecodecamp/search?query=python%20for%20beginners",
    skills: ["python"],
    level: "beginner",
    cost: "free",
    durationHours: 5,
    format: "tutorial",
    description: "A freeCodeCamp Python learning path for syntax, scripting, and first practical projects.",
  },
  {
    id: "youtube-freecodecamp-sql",
    provider: "YouTube",
    title: "SQL Full Course",
    url: "https://www.youtube.com/@freecodecamp/search?query=sql%20full%20course",
    skills: ["sql", "data-analysis"],
    level: "beginner",
    cost: "free",
    durationHours: 4,
    format: "tutorial",
    description: "A freeCodeCamp SQL tutorial for querying, joins, aggregation, and database basics.",
  },
  {
    id: "youtube-stanford-machine-learning",
    provider: "YouTube",
    title: "Stanford Online Machine Learning Lectures",
    url: "https://www.youtube.com/@stanfordonline/search?query=machine%20learning",
    skills: ["machine-learning", "data-analysis"],
    level: "intermediate",
    cost: "free",
    durationHours: 20,
    format: "playlist",
    description: "Stanford machine learning lectures for a more academic treatment of core ML concepts.",
  },
  {
    id: "youtube-3blue1brown-neural-networks",
    provider: "YouTube",
    title: "Neural Networks Visual Introduction",
    url: "https://www.youtube.com/@3blue1brown/search?query=neural%20networks",
    skills: ["machine-learning"],
    level: "beginner",
    cost: "free",
    durationHours: 3,
    format: "playlist",
    description: "Visual explanations of neural networks and gradient descent that make ML intuition easier to build.",
  },
  {
    id: "youtube-traversy-react",
    provider: "YouTube",
    title: "React Crash Course",
    url: "https://www.youtube.com/@TraversyMedia/search?query=react%20crash%20course",
    skills: ["react", "javascript"],
    level: "beginner",
    cost: "free",
    durationHours: 3,
    format: "tutorial",
    description: "A practical React overview for components, props, state, and small app development.",
  },
  {
    id: "youtube-fireship-typescript",
    provider: "YouTube",
    title: "TypeScript in 100 Seconds and Beyond",
    url: "https://www.youtube.com/@Fireship/search?query=typescript",
    skills: ["typescript", "javascript"],
    level: "beginner",
    cost: "free",
    durationHours: 2,
    format: "tutorial",
    description: "Fast TypeScript explanations and examples for JavaScript developers moving to typed code.",
  },
  {
    id: "youtube-netninja-power-bi",
    provider: "YouTube",
    title: "Power BI Tutorial Series",
    url: "https://www.youtube.com/@NetNinja/search?query=power%20bi",
    skills: ["power-bi", "data-analysis"],
    level: "beginner",
    cost: "free",
    durationHours: 4,
    format: "playlist",
    description: "A concise Power BI tutorial series for reports, models, and dashboard basics.",
  },
  {
    id: "udemy-python-bootcamp",
    provider: "Udemy",
    title: "Complete Python Bootcamp",
    url: "https://www.udemy.com/course/complete-python-bootcamp/",
    skills: ["python"],
    level: "beginner",
    cost: "paid",
    durationHours: 22,
    format: "course",
    description: "A practical Python bootcamp for learners who prefer project-heavy paid courses.",
  },
  {
    id: "udemy-modern-react-redux",
    provider: "Udemy",
    title: "Modern React with Redux",
    url: "https://www.udemy.com/course/react-redux/",
    skills: ["react", "javascript", "typescript"],
    level: "intermediate",
    cost: "paid",
    durationHours: 52,
    format: "course",
    description: "A deep React course for building production-style interfaces and state-driven applications.",
  },
  {
    id: "udemy-complete-sql-bootcamp",
    provider: "Udemy",
    title: "The Complete SQL Bootcamp",
    url: "https://www.udemy.com/course/the-complete-sql-bootcamp/",
    skills: ["sql", "data-analysis"],
    level: "beginner",
    cost: "paid",
    durationHours: 9,
    format: "course",
    description: "A hands-on SQL bootcamp for querying, joins, aggregation, and PostgreSQL-style analysis.",
  },
  {
    id: "udemy-tableau-data-visualization",
    provider: "Udemy",
    title: "Tableau Data Visualization Training",
    url: "https://www.udemy.com/topic/tableau/",
    skills: ["tableau", "data-analysis", "presentation"],
    level: "beginner",
    cost: "paid",
    durationHours: 12,
    format: "course",
    description: "Curated Tableau training options for dashboard building, charts, and business storytelling.",
  },
  {
    id: "udemy-agile-scrum-master",
    provider: "Udemy",
    title: "Agile Scrum Mastery",
    url: "https://www.udemy.com/topic/scrum/",
    skills: ["agile", "scrum", "project-management"],
    level: "beginner",
    cost: "paid",
    durationHours: 10,
    format: "course",
    description: "Scrum and agile delivery training for ceremonies, roles, artifacts, and delivery cadence.",
  },
  {
    id: "udemy-risk-management",
    provider: "Udemy",
    title: "Risk Management for Projects",
    url: "https://www.udemy.com/topic/risk-management/",
    skills: ["risk-management", "project-management"],
    level: "intermediate",
    cost: "paid",
    durationHours: 8,
    format: "course",
    description: "Focused risk management training for project identification, scoring, mitigation, and monitoring.",
  },
  {
    id: "coursera-excel-skills-business",
    provider: "Coursera",
    title: "Excel Skills for Business Specialization",
    url: "https://www.coursera.org/specializations/excel",
    skills: ["excel", "data-analysis", "budgeting"],
    level: "beginner",
    cost: "freemium",
    durationHours: 80,
    format: "specialization",
    description: "A structured Excel path for formulas, analysis, dashboards, and business reporting.",
  },
  {
    id: "coursera-finance-non-finance",
    provider: "Coursera",
    title: "Finance for Non-Finance Professionals",
    url: "https://www.coursera.org/learn/finance-for-non-finance",
    skills: ["budgeting", "strategic-planning"],
    level: "beginner",
    cost: "freemium",
    durationHours: 15,
    format: "course",
    description: "A practical finance course for budgeting, financial statements, and business decision-making.",
  },
  {
    id: "coursera-process-improvement",
    provider: "Coursera",
    title: "Six Sigma Yellow Belt Specialization",
    url: "https://www.coursera.org/specializations/six-sigma-fundamentals",
    skills: ["process-improvement", "data-analysis", "project-management"],
    level: "beginner",
    cost: "freemium",
    durationHours: 40,
    format: "specialization",
    description: "Process improvement, quality tools, and measurement fundamentals for operational roles.",
  },
  {
    id: "coursera-effective-communication",
    provider: "Coursera",
    title: "Effective Communication: Writing, Design, and Presentation",
    url: "https://www.coursera.org/specializations/effective-business-communication",
    skills: ["presentation", "stakeholder-management"],
    level: "beginner",
    cost: "freemium",
    durationHours: 40,
    format: "specialization",
    description: "A business communication path covering writing, slides, presentation, and audience clarity.",
  },
  {
    id: "coursera-strategic-leadership-management",
    provider: "Coursera",
    title: "Strategic Leadership and Management Specialization",
    url: "https://www.coursera.org/specializations/strategic-leadership",
    skills: ["leadership", "strategic-planning", "people-management"],
    level: "intermediate",
    cost: "freemium",
    durationHours: 80,
    format: "specialization",
    description: "Leadership and strategy training for managers moving into broader organizational responsibility.",
  },
  {
    id: "coursera-agile-leadership",
    provider: "Coursera",
    title: "Agile Leadership Specialization",
    url: "https://www.coursera.org/specializations/agile-leadership-change-management",
    skills: ["agile", "leadership", "stakeholder-management"],
    level: "intermediate",
    cost: "freemium",
    durationHours: 60,
    format: "specialization",
    description: "Agile leadership, change management, and team delivery practices for modern organizations.",
  },
  {
    id: "microsoft-project-management",
    provider: "Microsoft",
    title: "Use Microsoft Planner and Project for the Web",
    url: "https://learn.microsoft.com/en-us/training/browse/?terms=project%20management",
    skills: ["project-management", "programme-management"],
    level: "beginner",
    cost: "free",
    durationHours: 8,
    format: "course",
    description: "Microsoft learning modules for planning, tracking, and coordinating project work.",
  },
  {
    id: "microsoft-fabric-analytics",
    provider: "Microsoft",
    title: "Get Started with Microsoft Fabric",
    url: "https://learn.microsoft.com/en-us/training/paths/get-started-fabric/",
    skills: ["data-analysis", "power-bi", "sql"],
    level: "intermediate",
    cost: "free",
    durationHours: 12,
    format: "course",
    description: "Microsoft Fabric foundations for analytics, lakehouse concepts, reports, and integrated data workflows.",
  },
  {
    id: "amazon-well-architected",
    provider: "Amazon",
    title: "AWS Well-Architected Foundations",
    url: "https://aws.amazon.com/architecture/well-architected/",
    skills: ["aws", "risk-management", "strategic-planning"],
    level: "intermediate",
    cost: "free",
    durationHours: 8,
    format: "course",
    description: "AWS architecture principles for reliability, security, performance, cost, and operational excellence.",
  },
  {
    id: "amazon-cloud-essentials",
    provider: "Amazon",
    title: "AWS Cloud Essentials",
    url: "https://aws.amazon.com/training/learn-about/cloud-practitioner/",
    skills: ["aws"],
    level: "beginner",
    cost: "free",
    durationHours: 6,
    format: "course",
    description: "A concise introduction to cloud concepts, AWS services, and business value.",
  },
  {
    id: "coursera-product-management",
    provider: "Coursera",
    title: "Software Product Management Specialization",
    url: "https://www.coursera.org/specializations/product-management",
    skills: ["agile", "stakeholder-management", "strategic-planning"],
    level: "intermediate",
    cost: "freemium",
    durationHours: 60,
    format: "specialization",
    description: "Product planning, requirements, agile delivery, and stakeholder alignment for product roles.",
  },
  {
    id: "udemy-business-analysis",
    provider: "Udemy",
    title: "Business Analysis Fundamentals",
    url: "https://www.udemy.com/topic/business-analysis/",
    skills: ["stakeholder-management", "process-improvement", "presentation"],
    level: "beginner",
    cost: "paid",
    durationHours: 8,
    format: "course",
    description: "A practical business analysis path for requirements, processes, stakeholders, and documentation.",
  },
  {
    id: "youtube-fireship-aws",
    provider: "YouTube",
    title: "AWS Cloud Concepts",
    url: "https://www.youtube.com/@Fireship/search?query=aws",
    skills: ["aws"],
    level: "beginner",
    cost: "free",
    durationHours: 2,
    format: "tutorial",
    description: "Short-form AWS explanations for understanding core cloud concepts before deeper training.",
  },
] as const satisfies readonly LearningCourse[];
