export type TaxonomyEntry = {
  code: string;
  label: string;
  group?: string;
};

const entry = (code: string, label: string, group?: string): TaxonomyEntry => ({ code, label, group });

export const industries = [
  entry("tech-software", "Technology - Software", "Technology"),
  entry("tech-ai", "Artificial Intelligence and Machine Learning", "Technology"),
  entry("tech-cyber", "Cybersecurity", "Technology"),
  entry("tech-data", "Data and Analytics", "Technology"),
  entry("fintech", "Financial Technology", "Finance"),
  entry("banking", "Banking", "Finance"),
  entry("insurance", "Insurance", "Finance"),
  entry("investment", "Investment Management", "Finance"),
  entry("healthcare", "Healthcare", "Health"),
  entry("pharma", "Pharmaceuticals", "Health"),
  entry("biotech", "Biotechnology", "Health"),
  entry("medical-devices", "Medical Devices", "Health"),
  entry("education", "Education", "Public and Social"),
  entry("higher-education", "Higher Education", "Public and Social"),
  entry("government", "Government and Public Sector", "Public and Social"),
  entry("nonprofit", "Non-profit and NGO", "Public and Social"),
  entry("consulting", "Management Consulting", "Professional Services"),
  entry("legal", "Legal Services", "Professional Services"),
  entry("accounting", "Accounting and Audit", "Professional Services"),
  entry("hr", "Human Resources and Recruitment", "Professional Services"),
  entry("manufacturing", "Manufacturing", "Industrial"),
  entry("aerospace", "Aerospace and Defence", "Industrial"),
  entry("automotive", "Automotive", "Industrial"),
  entry("construction", "Construction and Built Environment", "Industrial"),
  entry("energy", "Energy and Utilities", "Infrastructure"),
  entry("renewables", "Renewable Energy", "Infrastructure"),
  entry("telecoms", "Telecommunications", "Infrastructure"),
  entry("transport", "Transport and Logistics", "Infrastructure"),
  entry("retail", "Retail and Ecommerce", "Consumer"),
  entry("consumer-goods", "Consumer Goods", "Consumer"),
  entry("hospitality", "Hospitality and Tourism", "Consumer"),
  entry("media", "Media and Entertainment", "Creative"),
  entry("marketing", "Marketing and Advertising", "Creative"),
  entry("design", "Design and Creative Services", "Creative"),
  entry("real-estate", "Real Estate", "Property"),
  entry("agriculture", "Agriculture and Food", "Primary Industries"),
  entry("environment", "Environment and Sustainability", "Primary Industries"),
] as const satisfies readonly TaxonomyEntry[];

export const careerLevels = [
  entry("entry", "Entry-level"),
  entry("early", "Early career"),
  entry("mid", "Mid-level"),
  entry("senior", "Senior"),
  entry("lead", "Lead / Principal"),
  entry("manager", "Manager"),
  entry("senior-manager", "Senior Manager"),
  entry("head", "Head of Function"),
  entry("director", "Director"),
  entry("vp", "VP / Vice President"),
  entry("c-suite", "C-Suite / Executive"),
] as const satisfies readonly TaxonomyEntry[];

export const jobTitles = [
  entry("software-engineer", "Software Engineer", "Engineering"),
  entry("senior-software-engineer", "Senior Software Engineer", "Engineering"),
  entry("frontend-developer", "Frontend Developer", "Engineering"),
  entry("backend-developer", "Backend Developer", "Engineering"),
  entry("full-stack-developer", "Full Stack Developer", "Engineering"),
  entry("devops-engineer", "DevOps Engineer", "Engineering"),
  entry("cloud-engineer", "Cloud Engineer", "Engineering"),
  entry("solutions-architect", "Solutions Architect", "Engineering"),
  entry("data-analyst", "Data Analyst", "Data"),
  entry("senior-data-analyst", "Senior Data Analyst", "Data"),
  entry("data-scientist", "Data Scientist", "Data"),
  entry("machine-learning-engineer", "Machine Learning Engineer", "Data"),
  entry("data-engineer", "Data Engineer", "Data"),
  entry("analytics-manager", "Analytics Manager", "Data"),
  entry("business-analyst", "Business Analyst", "Business"),
  entry("product-manager", "Product Manager", "Product"),
  entry("senior-product-manager", "Senior Product Manager", "Product"),
  entry("product-owner", "Product Owner", "Product"),
  entry("project-manager", "Project Manager", "Delivery"),
  entry("programme-manager", "Programme Manager", "Delivery"),
  entry("scrum-master", "Scrum Master", "Delivery"),
  entry("delivery-manager", "Delivery Manager", "Delivery"),
  entry("operations-manager", "Operations Manager", "Operations"),
  entry("business-operations-manager", "Business Operations Manager", "Operations"),
  entry("strategy-manager", "Strategy Manager", "Strategy"),
  entry("management-consultant", "Management Consultant", "Strategy"),
  entry("marketing-manager", "Marketing Manager", "Marketing"),
  entry("growth-manager", "Growth Manager", "Marketing"),
  entry("digital-marketing-manager", "Digital Marketing Manager", "Marketing"),
  entry("sales-manager", "Sales Manager", "Commercial"),
  entry("account-manager", "Account Manager", "Commercial"),
  entry("customer-success-manager", "Customer Success Manager", "Commercial"),
  entry("financial-analyst", "Financial Analyst", "Finance"),
  entry("finance-manager", "Finance Manager", "Finance"),
  entry("risk-manager", "Risk Manager", "Finance"),
  entry("compliance-manager", "Compliance Manager", "Governance"),
  entry("hr-business-partner", "HR Business Partner", "People"),
  entry("talent-acquisition-manager", "Talent Acquisition Manager", "People"),
  entry("learning-development-manager", "Learning and Development Manager", "People"),
  entry("ux-designer", "UX Designer", "Design"),
  entry("ui-designer", "UI Designer", "Design"),
  entry("product-designer", "Product Designer", "Design"),
  entry("content-designer", "Content Designer", "Design"),
  entry("researcher", "Researcher", "Research"),
  entry("lecturer", "Lecturer", "Education"),
  entry("teacher", "Teacher", "Education"),
  entry("nurse", "Nurse", "Health"),
  entry("clinical-project-manager", "Clinical Project Manager", "Health"),
  entry("supply-chain-manager", "Supply Chain Manager", "Operations"),
  entry("quality-manager", "Quality Manager", "Operations"),
  entry("engineering-manager", "Engineering Manager", "Leadership"),
  entry("head-of-data", "Head of Data", "Leadership"),
  entry("head-of-product", "Head of Product", "Leadership"),
  entry("chief-technology-officer", "Chief Technology Officer", "Executive"),
] as const satisfies readonly TaxonomyEntry[];

export const skillCategories = [
  entry("technical", "Technical"),
  entry("analytical", "Analytical"),
  entry("leadership", "Leadership"),
  entry("management", "Management"),
  entry("communication", "Communication"),
  entry("commercial", "Commercial"),
  entry("creative", "Creative"),
  entry("research", "Research"),
  entry("operations", "Operations"),
  entry("other", "Other"),
] as const satisfies readonly TaxonomyEntry[];

export const commonSkills = [
  entry("python", "Python", "Technical"),
  entry("sql", "SQL", "Technical"),
  entry("javascript", "JavaScript", "Technical"),
  entry("typescript", "TypeScript", "Technical"),
  entry("react", "React", "Technical"),
  entry("aws", "AWS", "Technical"),
  entry("azure", "Microsoft Azure", "Technical"),
  entry("power-bi", "Power BI", "Analytical"),
  entry("tableau", "Tableau", "Analytical"),
  entry("excel", "Microsoft Excel", "Analytical"),
  entry("data-analysis", "Data Analysis", "Analytical"),
  entry("machine-learning", "Machine Learning", "Analytical"),
  entry("project-management", "Project Management", "Management"),
  entry("programme-management", "Programme Management", "Management"),
  entry("agile", "Agile Delivery", "Management"),
  entry("scrum", "Scrum", "Management"),
  entry("stakeholder-management", "Stakeholder Management", "Communication"),
  entry("presentation", "Presentation Skills", "Communication"),
  entry("negotiation", "Negotiation", "Commercial"),
  entry("leadership", "Leadership", "Leadership"),
  entry("people-management", "People Management", "Leadership"),
  entry("strategic-planning", "Strategic Planning", "Leadership"),
  entry("risk-management", "Risk Management", "Management"),
  entry("budgeting", "Budgeting", "Commercial"),
  entry("process-improvement", "Process Improvement", "Operations"),
] as const satisfies readonly TaxonomyEntry[];

export const proficiencyLevels = [
  entry("beginner", "Beginner"),
  entry("intermediate", "Intermediate"),
  entry("advanced", "Advanced"),
  entry("expert", "Expert"),
] as const satisfies readonly TaxonomyEntry[];

export const educationDegrees = [
  entry("gcse", "GCSE / Secondary School"),
  entry("a-level", "A-Level / Sixth Form"),
  entry("btec", "BTEC / Vocational Qualification"),
  entry("foundation", "Foundation Degree"),
  entry("ba", "BA"),
  entry("bsc", "BSc"),
  entry("beng", "BEng"),
  entry("llb", "LLB"),
  entry("ma", "MA"),
  entry("msc", "MSc"),
  entry("meng", "MEng"),
  entry("mba", "MBA"),
  entry("mphil", "MPhil"),
  entry("phd", "PhD / Doctorate"),
  entry("certificate", "Professional Certificate"),
  entry("diploma", "Professional Diploma"),
] as const satisfies readonly TaxonomyEntry[];

export const fieldsOfStudy = [
  entry("computer-science", "Computer Science", "STEM"),
  entry("data-science", "Data Science", "STEM"),
  entry("artificial-intelligence", "Artificial Intelligence", "STEM"),
  entry("engineering", "Engineering", "STEM"),
  entry("business", "Business Administration", "Business"),
  entry("management", "Management", "Business"),
  entry("finance", "Finance", "Business"),
  entry("accounting", "Accounting", "Business"),
  entry("economics", "Economics", "Business"),
  entry("marketing", "Marketing", "Business"),
  entry("law", "Law", "Social Sciences"),
  entry("psychology", "Psychology", "Social Sciences"),
  entry("education", "Education", "Social Sciences"),
  entry("healthcare", "Healthcare", "Health"),
  entry("nursing", "Nursing", "Health"),
  entry("medicine", "Medicine", "Health"),
  entry("design", "Design", "Creative"),
  entry("media", "Media and Communications", "Creative"),
] as const satisfies readonly TaxonomyEntry[];

export const commonCertifications = [
  entry("pmp", "Project Management Professional (PMP)", "Project Management"),
  entry("prince2", "PRINCE2", "Project Management"),
  entry("scrum-master", "Certified ScrumMaster (CSM)", "Agile"),
  entry("psm", "Professional Scrum Master", "Agile"),
  entry("aws-cloud-practitioner", "AWS Certified Cloud Practitioner", "Cloud"),
  entry("aws-solutions-architect", "AWS Certified Solutions Architect", "Cloud"),
  entry("azure-fundamentals", "Microsoft Azure Fundamentals", "Cloud"),
  entry("azure-admin", "Microsoft Azure Administrator", "Cloud"),
  entry("google-data-analytics", "Google Data Analytics Certificate", "Data"),
  entry("power-bi", "Microsoft Power BI Data Analyst", "Data"),
  entry("cissp", "CISSP", "Security"),
  entry("security-plus", "CompTIA Security+", "Security"),
  entry("itil", "ITIL Foundation", "Service Management"),
  entry("six-sigma", "Lean Six Sigma Green Belt", "Operations"),
  entry("cipd", "CIPD", "People"),
  entry("acca", "ACCA", "Finance"),
  entry("cima", "CIMA", "Finance"),
] as const satisfies readonly TaxonomyEntry[];

export const workModes = [
  entry("remote", "Remote"),
  entry("hybrid", "Hybrid"),
  entry("onsite", "On-site"),
  entry("no-preference", "No preference"),
] as const satisfies readonly TaxonomyEntry[];

export const learningStyles = [
  entry("self-paced", "Self-paced"),
  entry("instructor-led", "Instructor-led"),
  entry("cohort", "Cohort-based"),
  entry("project-based", "Project-based"),
  entry("mentored", "Mentored coaching"),
  entry("blended", "Blended learning"),
] as const satisfies readonly TaxonomyEntry[];

export const currencies = [
  entry("gbp", "GBP - British Pound"),
  entry("usd", "USD - US Dollar"),
  entry("eur", "EUR - Euro"),
  entry("cad", "CAD - Canadian Dollar"),
  entry("aud", "AUD - Australian Dollar"),
  entry("ngn", "NGN - Nigerian Naira"),
  entry("inr", "INR - Indian Rupee"),
] as const satisfies readonly TaxonomyEntry[];

export * from "./courses";
