import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import profileRouter from "./profile";
import workExperiencesRouter from "./work-experiences";
import educationRouter from "./education";
import skillsRouter from "./skills";
import certificationsRouter from "./certifications";
import careerGoalRouter from "./career-goal";
import analysisRouter from "./analysis";
import roadmapRouter from "./roadmap";
import milestonesRouter from "./milestones";
import dashboardRouter from "./dashboard";
import journeyRouter from "./journey";
import advisorsRouter from "./advisors";
import remindersRouter from "./reminders";
import onboardingRouter from "./onboarding";
import certificatesRouter from "./certificates";
import taxonomyRouter from "./taxonomy";
import careerIntelligenceRouter from "./career-intelligence";
import careerProfileRouter from "./career-profile";
import careerPlanningRouter from "./career-planning";
import careerDataRouter from "./career-data";
import opportunitiesRouter from "./opportunities";
import applicationIntelligenceRouter from "./application-intelligence";
import interviewIntelligenceRouter from "./interview-intelligence";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(profileRouter);
router.use(workExperiencesRouter);
router.use(educationRouter);
router.use(skillsRouter);
router.use(certificationsRouter);
router.use(careerGoalRouter);
router.use(analysisRouter);
router.use(roadmapRouter);
router.use(milestonesRouter);
router.use(dashboardRouter);
router.use(journeyRouter);
router.use(advisorsRouter);
router.use(remindersRouter);
router.use(onboardingRouter);
router.use(certificatesRouter);
router.use(taxonomyRouter);
router.use(careerIntelligenceRouter);
router.use(careerProfileRouter);
router.use(careerPlanningRouter);
router.use(careerDataRouter);
router.use(opportunitiesRouter);
router.use(applicationIntelligenceRouter);
router.use(interviewIntelligenceRouter);

export default router;
